name: Generate Snake Game

on:
  schedule:
    - cron: '0 0 * * *' # Executa todos os dias à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate snake game
        uses: Platane/snk@master
        with:
          github_user_name: seu-usuario
          svg_out_path: dist/github-contribution-grid-snake.svg
          color: '#8A2BE2' # Cor roxo neon para a cobrinha
          background_color: '#000000' # Cor preta para os quadradinhos
